### ISSUE TITLE
This is V6 mod or V7 mod?

### ISSUE THREAD

**Issue by TheNickname99** [xzxADIxzx/Scheme-Size#11]
/google translate, (but not in title)---->/This mod has long been too "new" for the play store version, and that's understandable, but it's too old for the "pre alpha 7" version.  At the same time, this mod is also updated for some reason.  How to run it?  He is useless.

**Comment by xzxADIxzx** [comment]
> /google translate

Where are you from? I can speak English and Russian.

> It's too old for the *pre alpha 7*

I'm on build 135.2 so I'm making a mod for it.

> This mod is also updated for some reason

At the moment I am working on a global rework of the code, because there are a lot of *crutches*, inconsistencies and for the entire life of the mod I have never refactored it.

*P.S. Sorry for too late reply...*

**Comment by TheNickname99** [comment]
Thanks for the reply. I'm from the Russian, so... Мне легче говорить на русском :)

**Comment by xzxADIxzx** [comment]
А я из беларуси, к слову :3
